repositories:
- name: postgresql
  url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
- name: sonarqube
  url: https://SonarSource.github.io/helm-chart-sonarqube

releases:
- name: sonarqube-dce
  namespace: sonarqube-dce
  chart: sonarqube/sonarqube-dce
  version: 2025.1.3
  values:
  - dev/sonarqube-dce/values.yaml
