repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: sonarqube
  url: https://SonarSource.github.io/helm-chart-sonarqube

releases:
- name: kube-prometheus-stack
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  version: 62.7.0
- name: sonarqube
  namespace: sonarqube
  chart: sonarqube/sonarqube
  version: 10.6.1+3163
  values:
  - dev/sonarqube/values.yaml
- name: sonarqube
  namespace: sonarqube-dce
  chart: sonarqube/sonarqube-dce
  version: 10.7.0+3598
  values:
  - dev/sonarqube-dce/values.yaml
