applicationNodes:
  jwtSecret: "vzrZvlfYpkHqdxXdzPbuNvxkSToQsXRMxrc1zonlkl0="

  prometheusExporter:
    enabled: true

  prometheusMonitoring:
    podMonitor:
      enabled: true
      labels:
        release: "kube-prometheus-stack"

  resources:
    limits:
      memory: "2G"
    requests:
      cpu: "800m"
      memory: "2G"

  sonarProperties:
    sonar.log.level: DEBUG

    sonar.ce.javaOpts: "-Xmx2G"
    sonar.web.javaOpts: "-Xmx512M"

logging:
  jsonOutput: true

monitoringPasscode: "123456"

searchNodes:
  resources:
    limits:
      memory: "3G"
    requests:
      cpu: "400m"
      memory: "3G"

  sonarProperties:
    sonar.log.level: DEBUG
    sonar.search.javaOpts: "-Xms2G -Xmx2G"
