ApplicationNodes:
  jwtSecret: ""  # FIXME

  sonarProperties:
    sonar.log.level: DEBUG
    #sonar.security.realm: LDAP

ingress-nginx:
  enabled: true

ingress:
  enabled: true
  hosts:
    - name: sonarqube.aks.sonarsource.org

logging:
  jsonOutput: true
