applicationNodes:
  jwtSecret: "vzrZvlfYpkHqdxXdzPbuNvxkSToQsXRMxrc1zonlkl0="

  plugins:
    install:
      - "https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/5.0.0/sonar-dependency-check-plugin-5.0.0.jar"

    netrcCreds: "sonarqube-dce-sonarqube-dce-netrc" # k create secret generic sonarqube-dce-sonarqube-dce-netrc --from-file=netrc=~/.netrc

  prometheusExporter:
    enabled: true

  prometheusMonitoring:
    podMonitor:
      enabled: true
      labels:
        release: "kube-prometheus-stack"

  resources:
    limits:
      memory: "3G"
    requests:
      cpu: "800m"
      memory: "3G"

  sonarProperties:
    sonar.log.level: DEBUG

    sonar.ce.javaOpts: "-Xmx2G"
    sonar.web.javaOpts: "-Xmx512M"

logging:
  jsonOutput: true

monitoringPasscode: "123456"

searchNodes:
  resources:
    limits:
      memory: "5G"
    requests:
      cpu: "400m"
      memory: "5G"

  sonarProperties:
    sonar.search.javaOpts: "-Xms4G -Xmx4G"
