edition: "enterprise"

monitoringPasscode: "123456"

prometheusExporter:
  enabled: true
  podMonitor:
    enabled: true

prometheusMonitoring:
  podMonitor:
    enabled: true
    labels:
      release: "kube-prometheus-stack"

sonarProperties:
  sonar.log.level: DEBUG

  sonar.ce.javaOpts: "-Xmx2G"
  sonar.search.javaOpts: "-Xms2G -Xmx2G"
  sonar.web.javaOpts: "-Xmx512M"
